<template>
  <component :is="iconComponent" :size="size" :class="className" />
</template>

<script setup>
import { computed } from 'vue'
import {
  LayoutDashboard,
  CreditCard,
  Target,
  FolderOpen,
  LogOut,
  Menu,
  Wallet,
  Utensils,
  Car,
  ShoppingBag,
  Film,
  HeartPulse,
  GraduationCap,
  FileText,
  Banknote,
  TrendingUp,
  Gift,
  Plane,
  Home,
  Pin,
  Dumbbell,
  Coffee,
  Pencil,
  Trash2,
  Loader2,
  Plus,
  ArrowRight,
  X,
  ChevronDown,
  Calendar,
  Tag,
  DollarSign,
  TrendingDown,
  PieChart,
  BarChart3,
  List,
  Settings,
  User,
  Search,
  Filter,
  MoreVertical,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  Trash,
  Edit,
  Eye,
  EyeOff,
  ChevronLeft,
  ChevronRight,
  PlusCircle,
  MinusCircle,
  Bot,
  MessageSquare,
  Send,
  PiggyBank,
  Landmark,
  Smartphone,
  Briefcase,
  Building2,
  Coins,
  Star,
  Cat,
  Baby,
  Phone,
  Wifi,
  Gamepad2,
  BookOpen,
  Fuel,
  ParkingCircle,
  Wrench,
  Sparkles,
  Shirt,
  Footprints,
  Monitor,
  Sofa,
  UtensilsCrossed,
  TreePine,
  Trophy,
  Palette,
  HeartHandshake,
  Receipt,
  Shield,
  Pill,
  Stethoscope,
  Smile,
  Laptop,
  RotateCcw,
  Percent,
  PartyPopper,
  Zap,
  Bus,
  Train,
  Bike,
  PlaneTakeoff,
  Hotel,
  Ticket,
  Popcorn,
  Music,
  Camera,
  ShoppingCart,
  Package,
  Truck,
  MapPin,
  Navigation,
  ScanLine,
} from 'lucide-vue-next'

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  size: {
    type: [Number, String],
    default: 20,
  },
  className: {
    type: String,
    default: '',
  },
})

const iconMap = {
  // Navigation icons
  'dashboard': LayoutDashboard,
  'transactions': CreditCard,
  'budgets': Target,
  'categories': FolderOpen,
  'logout': LogOut,
  'menu': Menu,
  
  // Category icons
  'wallet': Wallet,
  'food': Utensils,
  'transport': Car,
  'car': Car,
  'shopping': ShoppingBag,
  'entertainment': Film,
  'health': HeartPulse,
  'education': GraduationCap,
  'bills': FileText,
  'salary': Banknote,
  'investment': TrendingUp,
  'gift': Gift,
  'travel': Plane,
  'home': Home,
  'other': Pin,
  'fitness': Dumbbell,
  'coffee': Coffee,
  
  // Action icons
  'pencil': Pencil,
  'trash': Trash2,
  'delete': Trash2,
  'edit': Pencil,
  'loader': Loader2,
  'loading': Loader2,
  'plus': Plus,
  'arrow-right': ArrowRight,
  'x': X,
  'chevron-down': ChevronDown,
  'calendar': Calendar,
  'tag': Tag,
  'dollar': DollarSign,
  'dollar-sign': DollarSign,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'pie-chart': PieChart,
  'bar-chart': BarChart3,
  'list': List,
  'settings': Settings,
  'user': User,
  'search': Search,
  'filter': Filter,
  'more-vertical': MoreVertical,
  'alert-circle': AlertCircle,
  'check-circle': CheckCircle2,
  'x-circle': XCircle,
  'info': Info,
  'eye': Eye,
  'eye-off': EyeOff,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'plus-circle': PlusCircle,
  'minus-circle': MinusCircle,
  'bot': Bot,
  'message-square': MessageSquare,
  'send': Send,
  'piggy-bank': PiggyBank,
  'landmark': Landmark,
  'smartphone': Smartphone,
  'credit-card': CreditCard,
  'coins': Coins,
  'building-2': Building2,
  'briefcase': Briefcase,
  'wallet-2': Wallet,
  'star': Star,
  // Additional category icons
  'pets': Cat,
  'baby': Baby,
  'phone': Phone,
  'internet': Wifi,
  'game': Gamepad2,
  'book': BookOpen,
  'gas': Fuel,
  'parking': ParkingCircle,
  'repair': Wrench,
  'beauty': Sparkles,
  'clothing': Shirt,
  'shoes': Footprints,
  'electronics': Monitor,
  'furniture': Sofa,
  'kitchen': UtensilsCrossed,
  'garden': TreePine,
  'sport': Trophy,
  'hobby': Palette,
  'charity': HeartHandshake,
  'tax': Receipt,
  'insurance': Shield,
  'medicine': Pill,
  'doctor': Stethoscope,
  'dentist': Smile,
  'freelance': Laptop,
  'refund': RotateCcw,
  'rental': Home,
  'business': Briefcase,
  'interest': Percent,
  'bonus': PartyPopper,
  'electricity': Zap,
  'bus': Bus,
  'train': Train,
  'bike': Bike,
  'flight': PlaneTakeoff,
  'plane': Plane,
  'hotel': Hotel,
  'ticket': Ticket,
  'movie': Popcorn,
  'music': Music,
  'camera': Camera,
  'cart': ShoppingCart,
  'package': Package,
  'delivery': Truck,
  'location': MapPin,
  'navigation': Navigation,
  'scan-line': ScanLine,
  'camera': Camera,
}

const iconComponent = computed(() => {
  return iconMap[props.name] || Wallet
})
</script>
